image: node:12

stages:
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  
before_script:
   - npm install
   - npm rebuild

unit tests:
  stage: test
  script:
  - echo "test"

integration test:
  stage: test
  script:
  - echo "test"

build:
  stage: build
  script:
   - npm run build

deploy build:
  stage: deploy
  script:
   - echo "Save artifacts"
  artifacts:
    paths:
    - build/
    expire_in: 1 week
