image: node:12

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

install_dependencies:
  stage: prepare_test
  script:
   - npm install

unit_test:
  stage: test
  script:
  - echo "test"

integration_test:
  stage: test
  script:
  - echo "test"

build:
  stage: build
  script:
   - npm run build
  artifacts:
    paths:
    - build/
    expire_in: 1 week
