image: node:12

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

install_dependencies:
  script:
   - npm install

build:
  script:
   - npm run build
  artifacts:
    paths:
    - build/
    expire_in: 1 week
