language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

os:
  - linux
  - osx

node_js:
  - 9

install:
  - npm install

before_script:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3;  fi"

#after_success:
#  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
#  - chmod +x send.sh
#  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL